package com.kh.finalGudok.member.vo;

import java.io.Serializable;

public class Member implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 8390133606096802210L;

	
}


MEMBER_NO	NUMBER
MEMBER_ID	VARCHAR2(50 BYTE)
EMAIL	VARCHAR2(100 BYTE)
MEMBER_PWD	VARCHAR2(30 BYTE)
MEMBER_NAME	VARCHAR2(15 BYTE)
PHONE	VARCHAR2(13 BYTE)
ADDRESS_1	VARCHAR2(100 BYTE)
ADDRESS_2	VARCHAR2(100 BYTE)
ADDRESS_3	VARCHAR2(100 BYTE)
GENDER	VARCHAR2(10 BYTE)
ENROLL_DATE	DATE
MODIFY_DATE	DATE
MEMBER_STATUS	VARCHAR2(3 BYTE)
EMAIL_STATUS	VARCHAR2(3 BYTE)
POINT	NUMBER
GRADE_NO	NUMBER